name: Unit checks

on:
  push:
    branches:
     - master
     
jobs:
  build:
    name: Lua ${{ matrix.luaVersion }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion:
         - 5.1
         - 5.2
         - 5.3
         - 5.4
    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - name: build
        run: |
          luarocks install busted
          luarocks make

      - name: test
        run: |
          lua -v
          busted test/*
